FROM openjdk:8

WORKDIR /thumbnailer

COPY . /thumbnailer

# Add entry-point.sh
COPY entry-point.sh /thumbnailer/entry-point.sh
RUN chmod +x /thumbnailer/entry-point.sh

ENTRYPOINT ["/thumbnailer/entry-point.sh"]
